# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location_data',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=300)),
                ('lattitude', models.CharField(max_length=300)),
            ],
        ),
    ]
