# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='location_name',
            field=models.CharField(default=datetime.datetime(2018, 2, 1, 18, 34, 36, 199617, tzinfo=utc), max_length=600),
            preserve_default=False,
        ),
    ]
