# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_data_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='hygenic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location_data',
            name='infrastructure',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='location_data',
            name='overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location_data',
            name='safety',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
