# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180201_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
