# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180201_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='bad_count',
            field=models.IntegerField(default=0),
        ),
    ]
