# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20180202_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_data',
            name='hygiene',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='location_data',
            name='infrastructure',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='location_data',
            name='overall',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='location_data',
            name='safety',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
