# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20180202_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_data',
            old_name='location_name',
            new_name='location_address',
        ),
    ]
