# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20180203_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='location_name',
            field=models.CharField(default='Swachh Public Toilet', max_length=300),
        ),
    ]
