# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_location_data_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='f',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='location_data',
            name='m',
            field=models.IntegerField(default=1),
        ),
    ]
