# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20180203_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='hours',
            field=models.CharField(default='5AM 10PM', max_length=300),
        ),
    ]
