# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_data',
            name='image_url',
            field=models.ImageField(default='media/default.img', upload_to='media/'),
        ),
    ]
