# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_auto_20180203_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_data',
            name='lattitude',
            field=models.FloatField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location_data',
            name='longitude',
            field=models.FloatField(max_length=300),
        ),
    ]
