# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_auto_20180203_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_data',
            name='d',
            field=models.IntegerField(default=1),
        ),
    ]
