# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_key_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', tinymce.models.HTMLField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
