# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_location_data_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_data',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='location.location_data')),
            ],
        ),
    ]
