# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_data',
            name='hygenic',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='review_data',
            name='infrastructure',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='review_data',
            name='overall',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='review_data',
            name='safety',
            field=models.FloatField(default=3.0),
        ),
    ]
