# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180201_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_data',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 2, 1, 20, 8, 2, 699249, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review_data',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 1, 20, 8, 13, 774911, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
