# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20180201_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_data',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review_data',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
