# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20180202_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_data',
            old_name='hygenic',
            new_name='hygiene',
        ),
    ]
