# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20180202_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_data',
            name='location_id',
            field=models.IntegerField(),
        ),
    ]
