# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20180202_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_data',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
    ]
