# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('admin_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('admin_fname', models.CharField(blank=True, max_length=300, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=300, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('admin_lname', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
