# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incharge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incharge_data',
            old_name='location_alloated',
            new_name='location_allocated',
        ),
    ]
